<form id="stripe_billing_form" data-action="/charlotte/payment/stripe" name="stripe">
    <div class="row">
        <div class="col-xs-12">
            <span class="text-danger bg-danger payment-errors hidden"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <label>Zip code</label>
            <input type="text" data-stripe="address_zip"/>
        </div>
        <div class="col-xs-12">
            <label>Card Name</label>
            <input type="text" data-stripe="name"/>
        </div>
        <div class="col-xs-12">
            <label>Card Number</label>
            <input type="text" data-stripe="number"/>
        </div>
        <div class="col-xs-12">
            <label>CVC</label>
            <input type="text" data-stripe="card_cvc"/>
        </div>
        <div class="col-xs-12">
            <label>Exp Month</label>
            <input type="text" data-stripe="exp_month"/>
        </div>
        <div class="col-xs-12">
            <label>Exp Year</label>
            <input type="text" data-stripe="exp_year"/>
        </div>
        <div class="col-xs-12">
            <label>Card Token (generated by Stripe)</label>
            <input type="text" id="stripe-card_token" name="token" data-stripe="card_token"/>
        </div>
        <div class="col-xs-12">
            <input type="submit" value="Submit"/>
        </div>
    </div>
</form>


<?php $settings = \common\components\CurrentStore::getSettings(); ?>
<script>
    /**
     * Stripe Checkout
     */
    Stripe.setPublishableKey('<?php echo $settings['payment']->stripe_test_publishable_key; ?>');
    var $form           = $('form#stripe_billing_form');

    $('form#stripe_billing_form').bind('submit', function(e){
        e.preventDefault();
        $form.find('button[type="submit"]').prop('disabled', true);                 //disable input
        Stripe.card.createToken($form, stripeResponseHandler);                      //request token from Stripe
    });
    function stripeResponseHandler(status, response){
        if(response.error){
            $form.find('.payment-errors').removeClass('hidden');
            $form.find('.payment-errors').text(response.error.message);
            $form.find('button[type="submit"]').prop('disabled', false);                // Re-enable submission
        }else{
            var token = response.id;
            $form.find('input#stripe-card_token').val(token);                           //set token value
            $form.get(0).submit();
        }
    };
</script>